export const ActionTypes = {
    GET_PRODUCTS_REQUEST : "GET_PRODUCTS_REQUEST",
    GET_PRODUCTS_SUCCESS : "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_FAIL : "GET_PRODUCTS_FAIL",

    GET_PRODUCT_DETAILS_REQUEST : "GET_PRODUCT_DETAILS_REQUEST",
    GET_PRODUCT_DETAILS_SUCCESS:"GET_PRODUCT_DETAILS_SUCCESS",
    GET_PRODUCT_DETAILS_FAIL : "GET_PRODUCT_DETAILS_FAIL",
    GET_PRODUCT_DETAILS_RESET : "GET_PRODUCT_DETAILS_RESET",

    POST_PRODUCT_DETAILS_REQUEST:"POST_PRODUCT_DETAILS_REQUEST",
    POST_PRODUCT_DETAILS_SUCCESS:"POST_PRODUCT_DETAILS_SUCCESS",
    POST_PRODUCT_DETAILS_FAIL:"POST_PRODUCT_DETAILS_FAIL"
};